/** Storefront UI strings (single locale). */

export const en = {
  nav: {
    brand: "Velore",
    products: "Products",
    cart: "Cart",
    account: "Account",
    seller: "Seller",
    admin: "Admin",
    login: "Log in",
    register: "Sign up",
  },
  cart: {
    title: "Your cart",
    loading: "Loading your cart…",
    empty: "Your cart is empty.",
    emptyHint: "Add items from the catalog to get started.",
    browseProducts: "Continue shopping",
    each: "each",
    remove: "Remove",
    decreaseQty: "Decrease quantity",
    increaseQty: "Increase quantity",
    totalLabel: "Subtotal",
    proceedCheckout: "Proceed to checkout",
    guestHint: "You can check out as a guest, or",
    signInLink: "sign in",
    guestHintSuffix: "to link this order to your account.",
    addToCart: "Add to cart",
    adding: "Adding…",
    quantity: "Qty",
    addedToCart: "Added to cart.",
  },
  reviewForm: {
    rating: "Rating",
    starsWord: "stars",
    titleOptional: "Title (optional)",
    comment: "Comment",
    submit: "Submit review",
    submitting: "Submitting…",
    thanks: "Thanks — your review is live.",
  },
  accountNav: {
    profile: "Profile",
    payment: "Payment methods",
    reviews: "Reviews",
  },
  accountShell: { asideTitle: "Account" },
  order: {
    backAllOrders: "All orders",
    orderTitle: "Order",
    payment: "Payment method",
    paymentCard: "Card",
    paymentCod: "Cash on delivery",
    paymentStatus: "Payment status",
    shippingBlock: "Shipping",
    subtotal: "Subtotal",
    discount: "Discount",
    tax: "Tax",
    shipping: "Shipping",
    total: "Total",
    legacyNote:
      "Legacy order: line items shown without full historical pricing breakdown.",
    piece: "item",
    pieces: "items",
  },
  orderStatus: {
    pending: "Pending",
    confirmed: "Confirmed",
    processing: "Processing",
    shipped: "Shipped",
    delivered: "Delivered",
    cancelled: "Cancelled",
  },
  paymentStatus: {
    pending: "Awaiting payment",
    unpaid: "Unpaid",
    paid: "Paid",
    failed: "Failed",
  },
  auth: {
    loginTitle: "Log in",
    verifiedOk: "Your email is verified. You can sign in below.",
    registeredHint:
      "If you just registered, open the verification link from your inbox (or the pending page in dev), then sign in.",
    suspended: "This account is unavailable. Signing you out…",
    backHome: "Home",
    signOut: "Sign out",
    resendTitle: "Need a new verification link?",
    resendHint:
      "For email & password accounts only. Enter your email and we’ll resend a link when available.",
    resendSubmit: "Resend",
    resendSending: "Sending…",
    verificationLinkLabel: "Verification link:",
    googleHint:
      "If the button doesn’t work, ensure Google sign-in is enabled in your environment.",
    orEmail: "Or with email",
    email: "Email",
    password: "Password",
    signIn: "Sign in",
    signingIn: "Signing in…",
    continueGoogle: "Continue with Google",
    invalidCredentials: "Invalid email or password.",
    verifyEmailFirst:
      "Your password is correct, but you must verify your email first. Open the link from your inbox or the verification pending page (dev).",
    newUser: "New here?",
    createAccount: "Create an account",
  },
  verifyEmail: {
    title: "Verify your email",
    sentTo: "We sent a verification link to",
    yourAddress: "your address on file",
    afterVerify: "After verification you can sign in with email and password.",
    devTitle: "Quick verify (development)",
    devBody: "If email isn’t configured, open this link to finish verification:",
    backLogin: "Back to log in",
    invalidLinkTitle: "Invalid link",
    missingToken: "This URL doesn’t include a verification token.",
    verificationFailed: "Couldn’t verify email",
    linkExpired: "This link expired. Request a new one from the log in page.",
    linkInvalid: "This verification link is invalid or was already used.",
  },
  checkout: {
    loading: "Loading…",
    emptyCart: "Your cart is empty.",
    emptyCartHint:
      "Add items from the catalog, then return here to complete your purchase.",
    backToCart: "Back to cart",
    title: "Checkout",
    subtitleSignedIn:
      "You’re signed in — we’ll use your saved cart for this order.",
    subtitleGuest:
      "Guest checkout — you’ll get a secure confirmation page after placing the order.",
    summaryTitle: "Order summary",
    breakdownTitle: "Price breakdown",
    subtotal: "Subtotal",
    discount: "Discount",
    tax: "Tax",
    shipping: "Shipping",
    shippingFreeHint: "Free shipping on orders from",
    shippingNote: "Flat shipping applies below the free-shipping threshold.",
    total: "Total",
    contactTitle: "Contact & shipping",
    email: "Email",
    fullName: "Full name",
    phone: "Phone",
    address1: "Address line 1",
    address2: "Address line 2 (optional)",
    city: "City",
    region: "State / region",
    postal: "Postal code",
    country: "Country",
    paymentTitle: "Payment",
    codTitle: "Cash on delivery",
    codDesc:
      "Pay when you receive the order. Order stays processing until delivery.",
    cardTitle: "Card (online payment)",
    cardDesc:
      "Payment is confirmed according to store settings. Full card data is not stored in this form.",
    placeOrder: "Place order",
    proceedToPayment: "Proceed to payment",
    stripeRedirecting: "Redirecting to secure payment…",
    stripePaymentSuccessful: "Payment successful 🎉",
    stripeProcessingTitle: "Confirming your payment",
    stripeProcessingBody:
      "Your payment was received. We are creating your order — this usually takes a few seconds.",
    stripePollingNote:
      "Hang tight — you will be redirected to your receipt automatically.",
    stripeCanceledTitle: "Payment was canceled",
    stripeCanceledBody:
      "No charges were made. You can return to checkout and choose another payment method.",
    backToCheckout: "Back to checkout",
  },
  payment: {
    pageTitle: "Payment methods",
    pageIntro:
      "Add a card for faster checkout later, or set a default. You can remove any method anytime.",
    noMethods: "No saved payment methods yet.",
    defaultBadge: "Default",
    setDefault: "Set as default",
    remove: "Remove",
    formTitle: "Add a card",
    formIntro:
      "Enter the last four digits and expiry as shown on the card. Only limited details are stored for display.",
    label: "Label",
    brand: "Card brand",
    last4: "Last 4 digits",
    expMonth: "Expiry month",
    expYear: "Expiry year",
    save: "Save card",
    saving: "Saving…",
    added: "Card added.",
    expiresIn: "Expires",
    placeholderLabel: "e.g. My Visa",
    brandOther: "Other",
  },
  account: {
    profileTitle: "Profile",
    profileIntro: "Update your name, contact details, and shipping address.",
    reviewsTitle: "Reviews",
    reviewsIntro: "Your reviews for products you purchased or tried.",
    reviewsEmpty: "You haven’t posted any reviews yet.",
  },
  catalog: {
    title: "Products",
    intro: "Search and filter by name, category, and price.",
    searchLabel: "Search name",
    searchPlaceholder: "e.g. shirt, phone…",
    category: "Category",
    allCategories: "All categories",
    uncategorized: "Uncategorized",
    minPrice: "Min price",
    maxPrice: "Max price",
    pricePlaceholder: "0",
    apply: "Apply filters",
    clear: "Clear filters",
    noResults: "No products match your filters.",
    noProductsTitle: "No products yet",
    noProductsHint: "Check back soon or adjust your filters.",
    featured: "Featured",
  },
  productDetail: {
    backToCatalog: "All products",
    noDescription: "No description for this product.",
    inStock: "In stock",
    outOfStock: "Out of stock",
    reviewsTitle: "Reviews",
    ratingFrom: "Average",
    reviewWord: "review",
    reviewsWord: "reviews",
    noReviewsLine: "No reviews yet.",
    loginAfterLink: "Sign in to write reviews and check out faster.",
    writeReviewTitle: "Write a review",
    writeReviewHint:
      "This form appears for products you purchased with non-cancelled orders.",
    alreadyReviewed: "You already reviewed this product.",
    purchaseToReview: "Purchase this product from the store to leave a review.",
  },
  orders: {
    title: "Your orders",
    intro: "Track shipments and receipts for every purchase on your account.",
    empty: "No orders yet.",
    emptyHint: "When you place an order, it will appear here with status updates.",
    emptyCta: "Browse products",
  },
  registerPage: {
    title: "Create account",
    subtitlePrefix: "Already have an account?",
    subtitleLogin: "Log in",
    subtitleSuffix:
      "After sign-up you’ll verify your email before first credentials sign-in.",
    nameOptional: "Name (optional)",
    email: "Email",
    password: "Password",
    submit: "Create account",
    submitting: "Creating account…",
  },
  profileForm: {
    displayName: "Display name",
    phone: "Phone",
    address1: "Address line 1",
    address2: "Address line 2",
    city: "City",
    state: "State / region",
    postal: "Postal code",
    country: "Country",
    save: "Save profile",
    saving: "Saving…",
    saved: "Changes saved.",
  },
  productForm: {
    name: "Product name",
    slug: "URL slug (optional — derived from name if empty)",
    category: "Category",
    selectCategory: "Select category",
    description: "Description",
    price: "Price",
    stock: "Stock",
    images: "Image URLs (one per line or comma-separated)",
    imagePlaceholder: "https://example.com/image.jpg",
    saving: "Saving…",
    create: "Create product",
    update: "Update product",
    saved: "Saved.",
  },
  home: {
    kicker: "Simple, secure shopping",
    title: "Welcome to Velore",
    lead:
      "Browse products, add to cart, and check out easily. Save payment methods and addresses from your account.",
    viewProducts: "Browse products",
    createAccount: "Create account",
    login: "Log in",
    heroBadge: "New season · curated picks",
    heroTitle: "Everything you love,",
    heroTitleAccent: "one cart away",
    heroLead:
      "Discover quality products, transparent pricing, and checkout that works on any device — guest or signed in.",
    heroPrimaryCta: "Shop all products",
    heroSecondaryCta: "Create an account",
    trustShippingTitle: "Fast delivery",
    trustShippingBody: "Reliable shipping on every order.",
    trustSecureTitle: "Secure checkout",
    trustSecureBody: "Encrypted payments and clear order status.",
    trustSupportTitle: "Help when you need it",
    trustSupportBody: "Account tools and order history in one place.",
    picksTitle: "Staff picks",
    picksSubtitle: "A rotating selection from the catalog — updated by your store team.",
    emptyPicks: "Products will appear here once they are live in the catalog.",
  },
  admin: {
    dashboardTitle: "Dashboard",
    dashboardIntro: "Manage users, orders, and homepage content.",
    linkUsers: "Users",
    hintUsers: "Ban & soft delete",
    linkRoles: "Roles",
    hintRoles: "Catalog of assignable roles",
    linkOrders: "Orders",
    hintOrders: "Status & tracking",
    linkBanners: "Banners",
    hintBanners: "Homepage",
    linkCategories: "Categories",
    hintCategories: "Catalog structure",
    linkProducts: "Products",
    hintProducts: "Add & edit products",
    statUsers: "Users (active)",
    statProducts: "Products",
    statCategories: "Categories",
    statOrders: "Orders",
    ordersIntro: "Track orders, update status and tracking numbers.",
    ordersEmpty: "No orders match your filters yet.",
    usersIntro:
      "Banning blocks sign-in. Soft delete hides the account and also blocks sign-in.",
    bannersIntro: "Manage images and links on the homepage.",
    categoriesIntro: "Organize product categories in the catalog.",
    productsListIntro: "View and edit store products.",
    searchPlaceholder: "Search by email or name",
    trackingPlaceholder: "Carrier tracking number",
    pageOrdersTitle: "Orders",
    pageUsersTitle: "Users",
    pageBannersTitle: "Homepage banners",
    pageCategoriesTitle: "Categories",
    pageProductsTitle: "Products",
    pendingRevenue: "Pending revenue",
    backToProducts: "Products",
    thOrder: "Order",
    thCustomer: "Customer",
    thItems: "Items",
    thTotal: "Total",
    thStatus: "Status",
    thPayment: "Payment",
    showDeleted: "Show deleted",
    hideDeleted: "Hide deleted",
    paymentCodShort: "COD",
    paymentCardShort: "Card",
    thEmail: "Email",
    thName: "Name",
    thRole: "Role",
    thActions: "Actions",
    statusActive: "Active",
    statusBanned: "Banned",
    statusDeleted: "Deleted",
    ban: "Ban",
    unban: "Unban",
    softDelete: "Soft delete",
    restore: "Restore",
    youLabel: "You",
    searchButton: "Search",
    addUser: "Add user",
    addUserModalTitle: "Create user",
    addUserNameLabel: "Name",
    addUserEmailLabel: "Email",
    addUserPasswordLabel: "Password",
    addUserRoleLabel: "Role",
    addUserSubmit: "Create",
    addUserCreating: "Creating…",
    addUserCancel: "Cancel",
    roleUpdating: "Updating role…",
    toastRoleUpdated: "Role updated.",
    toastRoleFailed: "Could not update role.",
    toastUserCreated: "User created.",
    toastUserCreateFailed: "Could not create user.",
    rolesLoading: "Loading roles…",
    pageRolesTitle: "Roles",
    rolesIntro:
      "Core roles are created automatically. Add more by name; each gets a unique URL-safe slug used in user records.",
    rolesThSlug: "Slug",
    rolesThName: "Name",
    rolesAddLabel: "New role name",
    rolesAddPlaceholder: "e.g. Wholesale partner",
    rolesAddButton: "Add role",
    rolesCreating: "Saving…",
    rolesToastCreated: "Role added.",
    rolesToastError: "Could not add role.",
    delete: "Delete",
    yes: "Yes",
    no: "No",
    newProduct: "New product",
    thProductName: "Name",
    thProductCategory: "Category",
    thProductPrice: "Price",
    thStock: "Stock",
    thActive: "Active",
    edit: "Edit",
    deactivate: "Deactivate",
    noProductsYet: "No products yet. Create a category, then add a product.",
    sellerProductsIntro:
      "Manage store products. Categories are maintained in admin.",
    orderDetailBack: "All orders",
    orderDetailTitle: "Order",
    orderDetailItems: "Line items",
    orderDetailShipping: "Shipping & status",
    orderStatusLabel: "Order status",
    trackingLabel: "Tracking number",
    adminNotesLabel: "Internal notes",
    saveChanges: "Save changes",
    markedShipped: "Marked shipped at",
    backToProductList: "Back to product list",
    needCategoryFirst: "Create at least one category before adding products.",
    manageCategories: "Manage categories",
    newProductPageTitle: "New product",
    editProductPageTitle: "Edit product",
    sellerNeedCategories:
      "An admin must create categories before you can add products.",
    noCategoriesShort: "No categories. Create one first.",
  },
  checkoutSuccess: {
    thanks: "Thank you",
    generic:
      "We received your order. Keep your confirmation link or view orders in your account if signed in.",
    confirmedTitle: "Order confirmed",
    orderRef: "Order",
    items: "Items",
    total: "Total",
    paymentMethod: "Payment method",
    paymentCod: "Cash on delivery",
    paymentCard: "Card",
    paymentStatus: "Payment status",
    orderStatus: "Order status",
    receiptNote:
      "Keep this page URL for your records. Don’t share it with untrusted parties.",
    continue: "Continue shopping",
    cart: "View cart",
  },
  footer: {
    brand: "Velore",
    tagline: "Refined by design.",
  },
} as const;

export const checkoutErrors = {
  cartEmpty: "Your cart is empty.",
  invalidCartPayload: "Couldn’t read cart data.",
  invalidCartItems: "Cart line items are invalid.",
  completeShipping: "Please complete all contact and address fields.",
  productUnavailable: "A product is no longer available.",
  stockPrefix: "Insufficient stock for",
  useStripeCheckout:
    "Card payment uses the “Proceed to payment” button. Please select card payment and use that button.",
} as const;

export const paymentErrors = {
  unauthorized: "Please sign in.",
  invalidId: "Invalid id.",
  notFound: "Payment method not found.",
  invalidInput: "Couldn’t process the submitted data.",
  last4Digits: "Enter the last 4 digits of the card.",
} as const;

export const profileErrors = {
  unauthorized: "Please sign in.",
  invalidInput: "Couldn’t save. Check your fields.",
} as const;



